/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlogLayout: typeof import('./src/components/blogLayout.vue')['default']
    Buy: typeof import('./src/components/badge/buy.vue')['default']
    Card: typeof import('./src/components/card.vue')['default']
    CommentRow: typeof import('./src/components/comment/commentRow.vue')['default']
    Edit: typeof import('./src/components/badge/edit.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NProgress: typeof import('naive-ui')['NProgress']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NScrollBar: typeof import('naive-ui')['NScrollBar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    NThing: typeof import('naive-ui')['NThing']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/title/select.vue')['default']
    Sender: typeof import('./src/components/comment/sender.vue')['default']
    Tabbar: typeof import('./src/components/tabbar.vue')['default']
    TabbarBlog: typeof import('./src/components/tabbarBlog.vue')['default']
    User: typeof import('./src/components/user.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCol: typeof import('vant/es')['Col']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanRow: typeof import('vant/es')['Row']
    VanTag: typeof import('vant/es')['Tag']
    WeekPromote: typeof import('./src/components/weekPromote.vue')['default']
  }
}

// For TSX support
declare global {
  const BlogLayout: typeof import('./src/components/blogLayout.vue')['default']
  const Buy: typeof import('./src/components/badge/buy.vue')['default']
  const Card: typeof import('./src/components/card.vue')['default']
  const CommentRow: typeof import('./src/components/comment/commentRow.vue')['default']
  const Edit: typeof import('./src/components/badge/edit.vue')['default']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NDatePicker: typeof import('naive-ui')['NDatePicker']
  const NDivider: typeof import('naive-ui')['NDivider']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NGi: typeof import('naive-ui')['NGi']
  const NGrid: typeof import('naive-ui')['NGrid']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NInput: typeof import('naive-ui')['NInput']
  const NPopconfirm: typeof import('naive-ui')['NPopconfirm']
  const NProgress: typeof import('naive-ui')['NProgress']
  const NRadio: typeof import('naive-ui')['NRadio']
  const NRadioGroup: typeof import('naive-ui')['NRadioGroup']
  const NScrollbar: typeof import('naive-ui')['NScrollbar']
  const NScrollBar: typeof import('naive-ui')['NScrollBar']
  const NSelect: typeof import('naive-ui')['NSelect']
  const NSpin: typeof import('naive-ui')['NSpin']
  const NTag: typeof import('naive-ui')['NTag']
  const NThing: typeof import('naive-ui')['NThing']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Select: typeof import('./src/components/title/select.vue')['default']
  const Sender: typeof import('./src/components/comment/sender.vue')['default']
  const Tabbar: typeof import('./src/components/tabbar.vue')['default']
  const TabbarBlog: typeof import('./src/components/tabbarBlog.vue')['default']
  const User: typeof import('./src/components/user.vue')['default']
  const VanButton: typeof import('vant/es')['Button']
  const VanCol: typeof import('vant/es')['Col']
  const VanField: typeof import('vant/es')['Field']
  const VanIcon: typeof import('vant/es')['Icon']
  const VanRow: typeof import('vant/es')['Row']
  const VanTag: typeof import('vant/es')['Tag']
  const WeekPromote: typeof import('./src/components/weekPromote.vue')['default']
}