packages:
  - ./*
shamefullyHoist: true
shellEmulator: true
sideEffectsCache: false
strictPeerDependencies: false
catalog:
  "@capacitor/android": ^7.4.3
  "@capacitor/app": ^7.1.0
  "@capacitor/assets": ^3.0.5
  "@capacitor/cli": ^7.4.3
  "@capacitor/core": ^7.4.3
  "@capacitor/device": ^7.0.2
  "@capacitor/inappbrowser": ^2.5.1
  "@capacitor/screen-orientation": ^7.0.2
  "@capacitor/splash-screen": ^7.0.3
  "@capacitor/status-bar": ^7.0.3
  "@lhlyu/vue-virtual-waterfall": ^1.0.8
  "@tailwindcss/vite": ^4.1.13
  "@types/crypto-js": ^4.2.2
  "@vant/auto-import-resolver": ^1.3.0
  "@vant/use": ^1.6.0
  "@vicons/antd": ^0.13.0
  "@vicons/material": ^0.13.0
  "@vitejs/plugin-legacy": ^7.2.1
  "@vitejs/plugin-vue": ^6.0.1
  "@vitejs/plugin-vue-jsx": ^5.1.1
  "@vue/tsconfig": ^0.8.1
  "@vueuse/core": ^13.9.0
  axios: ^1.12.2
  browserslist: ^4.26.2
  capacitor-plugin-safe-area: ^4.0.0
  color: ^5.0.2
  core-js: ^3.45.1
  crypto-js: ^4.2.0
  dayjs: ^1.11.18
  dexie: ^4.2.0
  dexie-relationships: ^1.2.11
  dompurify: ^3.2.7
  localforage: ^1.10.0
  lodash-es: ^4.17.21
  mitt: ^3.0.1
  motion-v: ^1.7.2
  naive-ui: ^2.43.1
  pinia: ^3.0.3
  sass-embedded: ^1.93.0
  swiper: ^12.0.2
  tailwindcss-safe-area-capacitor: ^0.5.1
  terser: ^5.44.0
  userscript-meta: ^1.0.1
  vant: ^4.9.21
  vite-plugin-conditional-compiler: ^0.3.1
  vite-plugin-copy-dts: ^0.0.6
  vite-plugin-dts: ^4.5.4
  vite-plugin-html: ^3.2.2
  vite-plugin-monkey: ^7.1.4
  vue: ^3.5.22
  vue-picture-cropper: ^0.7.0
  vue-router: ^4.5.1
  vue-tsc: ^3.1.0
